name: GitHub Action Slack Notify CI

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest

steps:
      - uses: actions/checkout@v1
      - name: Use Node.js v12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Notify slack
        # Don't attempt to send Slack notifications on fork PRs which don't have access to secrets
        if: env.SLACK_NOTIFICATIONS_BOT_TOKEN
        id: slack
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}
        uses: ./
        with:
          channel_id: C023KU91UPL
          status: STARTED
          color: warning
      - name: Notify slack success
        if: env.SLACK_BOT_TOKEN
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}
        uses: ./
        with:
          message_id: ${{ steps.slack.outputs.message_id }}
          channel_id: C023KU91UPL
          status: SUCCESS
          color: good
      - name: Notify slack fail
          if: failure()
          env:
            SLACK_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}
          uses: voxmedia/github-action-slack-notify-build@v1
          with:
            channel_id: C023KU91UPL
            status: FAILED
            color: danger
